pipeline {
    agent any
    environment {
        NAMESPACE = 'formazione-sou' // Namespace esistente
        KUBECONFIG = '/Users/anconitani/.kube/config'
    }
    parameters {
        string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Tag dell\'immagine Docker da rilasciare')
    }
    stages {
        stage('Configure Kubectl') {
            steps {
                sh 'kubectl config use-context minikube'
            }
        }
        stage('Checkout') {
            steps {
                checkout scm // Gestito automaticamente dalla multibranch pipeline
            }
        }
        stage('update Helm Dependencies') {
            steps {
                script {
                    dir('charts') {
                        // Add the repository if not already added
                        sh 'helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx'
                        // Update the repositories to ensure the latest charts are available
                        sh 'helm repo update'
                        // Fetch and update the chart dependencies
                        sh 'helm dependency update ./ --debug'
                    }
                }
            }
        }
        stage('Build Helm Dependencies') {
            steps {
                script {
                    dir('charts') {
                        // Build the Helm dependencies
                        sh 'helm dependency build ./ --debug'
                    }
                }
            }
        }
        stage('Install/Upgrade Helm Chart') {
            steps {
                script {
                    dir('charts') {
                        sh """
                        helm upgrade --install flask-app ./ \
                            --namespace ${NAMESPACE} \
                            --set image.tag=${params.IMAGE_TAG}
                        """
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'Pipeline completata con successo!'
        }
        failure {
            echo 'Pipeline fallita. Controlla i log per dettagli.'
        }
    }
}
