# values.yaml

image:
  repository: aanconitani/jenkins-app  # Il nome del repository Docker Hub
  tag: "latest"                       # Il tag dell'immagine (ad esempio "latest")
  pullPolicy: IfNotPresent            # La politica di pull per l'immagine

service:
  type: ClusterIP
  port: 5000

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  host: "flask-app.local"
  paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: {{ include "jenkins-app.fullname" . }}
          port:
            number: 5000
