# values.yaml

image:
  repository: aanconitani/jenkins-app  # Repository dell'immagine su Docker Hub
  tag: "latest"                       # Tag dell'immagine, che può essere specificato in fase di installazione
  pullPolicy: IfNotPresent            # Politica di pull dell'immagine

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  host: "flask-app.local"
  paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: {{ include "flask-app-example.fullname" . }}
          port:
            number: 5000
