---
# tasks file for jenkins

- name: Create Jenkins data volume 
  containers.podman.podman_volume:
    name: "{{ jenkins_data_volume }}"
    state: present

- name: Create Jenkins certs volume
  containers.podman.podman_volume:
    name: "{{ jenkins_cert_volume }}"
    state: present

- name: Run Jenkins Master
  containers.podman.podman_container:
    name: "{{ jenkins_master_name }}"
    image: "{{ jenkins_master_image }}"
    state: started
    detach: true
#    network_mode: host
    network: "{{ jenkins_network_name }}"
    ip: "{{ jenkins_master_static_ip }}"
    privileged: true
    publish:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "{{ jenkins_data_volume }}:/var/jenkins_home"
      - "{{ jenkins_cert_volume }}:/certs/client:ro"
      - "/run/podman/podman.sock:/run/podman/podman.sock"

